#pragma once

#include "nn/node/concat_node.h"
#include "nn/node/dino_decode_node.h"
#include "nn/node/identity_node.h"
#include "nn/node/input_node.h"
#include "nn/node/mean_node.h"
#include "nn/node/node_type.h"
#include "nn/node/sam_decode_node.h"
#include "nn/node/sam_prompt_encode_node.h"
#include "nn/node/split_arg_max_node.h"
#include "nn/node/split_node.h"
#include "nn/node/sum_node.h"
#include "nn/node/yolo26_raw_decode_node.h"
#include "nn/node/yolo26_ultralytics_decode_node.h"
#include "nn/node/yolo_decode_node.h"
#include "nn/node/yolo_e2e_decode_node.h"
#include "nn/node/yolov8_decode_node.h"
