#pragma once

namespace cosmo::nn {

typedef enum {
    NODE_INPUT = 0,
    NODE_RESIZE,
    NODE_CROP_RESIZE,
    NODE_AFFINE_CROP,
    NODE_SEQUENCE,
    NODE_NORMALIZE,
    NODE_COMBINE_IMAGE,
    NODE_DINO_ENCODE,

    NODE_NET,

    NODE_COPY,

    NODE_YOLO_DECODE,
    NODE_YOLO_NPU_DECODE,
    NODE_YOLOV8_DECODE,
    NODE_YOLO_E2E_DECODE,
    NODE_YOLO26_RAW_DECODE,
    NODE_IMAGE_TO_TENSOR,
    NODE_SPLIT,
    NODE_SPLIT_ARG_MAX,
    NODE_SUM,
    NODE_CONCAT,
    NODE_MEAN,
    NODE_DINO_DECODE,
    NODE_SAM_ENCODE,
    NODE_SAM_PROMPT_ENCODE,
    NODE_SAM_DECODE,
    NODE_IDENTITY,

    NODE_TYPE_COUNT,
    NODE_UNKNOWN = 999
} NodeType;

}
