set(CRYPTOPP_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rd/cryptopp-cmake-CRYPTOPP_8_9_0)
set(CRYPTOPP_INSTALL_DIR ${THIRDPARTY_INSTALL_PREFIX}/cryptopp)
set(CRYPTOPP_HEADERS ${CRYPTOPP_INSTALL_DIR}/include)
set(CRYPTOPP_LIB ${CRYPTOPP_INSTALL_DIR}/lib/libcryptopp.a)

ExternalProject_Add(
    cryptopp_external

    SOURCE_DIR ${CRYPTOPP_SOURCE_DIR}

    CMAKE_ARGS
        ${COSMO_EXTERNAL_PROJECT_CMAKE_ARGS}
        -DCMAKE_INSTALL_PREFIX=${CRYPTOPP_INSTALL_DIR}
        -DCRYPTOPP_SOURCES=${CMAKE_CURRENT_SOURCE_DIR}/3rd/cryptopp-CRYPTOPP_8_9_0
        -DCRYPTOPP_BUILD_TESTING=OFF
        -DCRYPTOPP_BUILD_DOCUMENTATION=OFF

    INSTALL_COMMAND ${CMAKE_COMMAND} --install . --prefix ${CRYPTOPP_INSTALL_DIR}

    UPDATE_COMMAND ""
    BUILD_ALWAYS OFF

    LOG_CONFIGURE ON
    LOG_BUILD ON
    LOG_INSTALL ON
    LOG_OUTPUT_ON_FAILURE ON
)

add_dependencies(third_build cryptopp_external)

add_library(cryptopp STATIC IMPORTED)
set_target_properties(cryptopp PROPERTIES
    IMPORTED_LOCATION ${CRYPTOPP_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${CRYPTOPP_HEADERS}"
)
add_dependencies(cryptopp cryptopp_external)
