set(_cosmo_legacy_arch_explicit FALSE)
if(DEFINED CACHE{COSMO_TARGET_ARCH})
    set(_cosmo_legacy_arch_explicit TRUE)
    set(_cosmo_legacy_arch_value "$CACHE{COSMO_TARGET_ARCH}")
endif()

set(_cosmo_legacy_nn_sophon_explicit FALSE)
if(DEFINED CACHE{COSMO_NN_USE_SOPHON_BACKEND})
    set(_cosmo_legacy_nn_sophon_explicit TRUE)
    set(_cosmo_legacy_nn_sophon_value "$CACHE{COSMO_NN_USE_SOPHON_BACKEND}")
endif()

set(_cosmo_legacy_nn_cpu_explicit FALSE)
if(DEFINED CACHE{COSMO_NN_USE_CPU_BACKEND})
    set(_cosmo_legacy_nn_cpu_explicit TRUE)
    set(_cosmo_legacy_nn_cpu_value "$CACHE{COSMO_NN_USE_CPU_BACKEND}")
endif()

set(_cosmo_legacy_media_sophon_explicit FALSE)
if(DEFINED CACHE{COSMO_MEDIA_USE_SOPHON_BACKEND})
    set(_cosmo_legacy_media_sophon_explicit TRUE)
    set(_cosmo_legacy_media_sophon_value "$CACHE{COSMO_MEDIA_USE_SOPHON_BACKEND}")
endif()

set(_cosmo_legacy_media_cpu_explicit FALSE)
if(DEFINED CACHE{COSMO_MEDIA_USE_CPU_BACKEND})
    set(_cosmo_legacy_media_cpu_explicit TRUE)
    set(_cosmo_legacy_media_cpu_value "$CACHE{COSMO_MEDIA_USE_CPU_BACKEND}")
endif()

set(COSMO_TARGET_PLATFORM "sophon" CACHE STRING "Target platform profile: x86, sophon, rk3588, or ascend310p3")
set_property(CACHE COSMO_TARGET_PLATFORM PROPERTY STRINGS x86 sophon rk3588 ascend310p3)

function(_cosmo_norm_bool out value)
    string(TOUPPER "${value}" _cosmo_bool_value)
    if(_cosmo_bool_value STREQUAL "ON" OR
       _cosmo_bool_value STREQUAL "TRUE" OR
       _cosmo_bool_value STREQUAL "1" OR
       _cosmo_bool_value STREQUAL "YES")
        set(${out} ON PARENT_SCOPE)
    else()
        set(${out} OFF PARENT_SCOPE)
    endif()
endfunction()

function(_cosmo_fail_legacy message_text)
    message(FATAL_ERROR "${message_text}")
endfunction()

string(TOLOWER "${COSMO_TARGET_PLATFORM}" COSMO_TARGET_PLATFORM)
if(NOT COSMO_TARGET_PLATFORM STREQUAL "x86" AND
   NOT COSMO_TARGET_PLATFORM STREQUAL "sophon" AND
   NOT COSMO_TARGET_PLATFORM STREQUAL "rk3588" AND
   NOT COSMO_TARGET_PLATFORM STREQUAL "ascend310p3")
    message(FATAL_ERROR
        "Unsupported COSMO_TARGET_PLATFORM=${COSMO_TARGET_PLATFORM}. Expected x86, sophon, rk3588, or ascend310p3.")
endif()

set(_cosmo_inferred_platform "${COSMO_TARGET_PLATFORM}")
set(_cosmo_used_legacy_inputs FALSE)

if(_cosmo_legacy_nn_cpu_explicit)
    _cosmo_norm_bool(_cosmo_nn_cpu_requested "${_cosmo_legacy_nn_cpu_value}")
    if(_cosmo_nn_cpu_requested)
        set(_cosmo_inferred_platform "x86")
        set(_cosmo_used_legacy_inputs TRUE)
    endif()
endif()

if(_cosmo_legacy_nn_sophon_explicit)
    _cosmo_norm_bool(_cosmo_nn_sophon_requested "${_cosmo_legacy_nn_sophon_value}")
    if(_cosmo_nn_sophon_requested)
        if(_cosmo_used_legacy_inputs AND NOT _cosmo_inferred_platform STREQUAL "sophon")
            _cosmo_fail_legacy("Legacy backend options request conflicting platforms. CPU implies x86, Sophon implies sophon.")
        endif()
        set(_cosmo_inferred_platform "sophon")
        set(_cosmo_used_legacy_inputs TRUE)
    endif()
endif()

if(_cosmo_legacy_media_cpu_explicit)
    _cosmo_norm_bool(_cosmo_media_cpu_requested "${_cosmo_legacy_media_cpu_value}")
    if(_cosmo_media_cpu_requested)
        if(_cosmo_used_legacy_inputs AND NOT _cosmo_inferred_platform STREQUAL "x86")
            _cosmo_fail_legacy("Legacy media backend options request conflicting platforms. CPU media implies x86.")
        endif()
        set(_cosmo_inferred_platform "x86")
        set(_cosmo_used_legacy_inputs TRUE)
    endif()
endif()

if(_cosmo_legacy_media_sophon_explicit)
    _cosmo_norm_bool(_cosmo_media_sophon_requested "${_cosmo_legacy_media_sophon_value}")
    if(_cosmo_media_sophon_requested)
        if(_cosmo_used_legacy_inputs AND NOT _cosmo_inferred_platform STREQUAL "sophon")
            _cosmo_fail_legacy("Legacy media backend options request conflicting platforms. Sophon media implies sophon.")
        endif()
        set(_cosmo_inferred_platform "sophon")
        set(_cosmo_used_legacy_inputs TRUE)
    endif()
endif()

if(_cosmo_legacy_arch_explicit)
    if(_cosmo_legacy_arch_value STREQUAL "x86_64")
        if(_cosmo_used_legacy_inputs AND NOT _cosmo_inferred_platform STREQUAL "x86")
            _cosmo_fail_legacy("COSMO_TARGET_ARCH=x86_64 conflicts with the selected legacy backend settings.")
        endif()
        set(_cosmo_inferred_platform "x86")
        set(_cosmo_used_legacy_inputs TRUE)
    elseif(_cosmo_legacy_arch_value STREQUAL "aarch64")
        if(_cosmo_used_legacy_inputs AND _cosmo_inferred_platform STREQUAL "x86")
            _cosmo_fail_legacy("COSMO_TARGET_ARCH=aarch64 conflicts with the selected legacy backend settings.")
        endif()
        if(NOT _cosmo_used_legacy_inputs)
            set(_cosmo_inferred_platform "sophon")
            set(_cosmo_used_legacy_inputs TRUE)
        endif()
    else()
        message(FATAL_ERROR "Unsupported COSMO_TARGET_ARCH=${_cosmo_legacy_arch_value}. Expected aarch64 or x86_64.")
    endif()
endif()

if(_cosmo_used_legacy_inputs)
    if(NOT COSMO_TARGET_PLATFORM STREQUAL "${_cosmo_inferred_platform}")
        message(FATAL_ERROR
            "COSMO_TARGET_PLATFORM=${COSMO_TARGET_PLATFORM} conflicts with legacy build options, which resolve to ${_cosmo_inferred_platform}.")
    endif()
    message(WARNING
        "Legacy build options (COSMO_TARGET_ARCH and/or backend toggles) are deprecated. "
        "Use COSMO_TARGET_PLATFORM=${_cosmo_inferred_platform} instead.")
endif()

if(COSMO_TARGET_PLATFORM STREQUAL "x86")
    set(COSMO_TARGET_ARCH "x86_64" CACHE STRING "Derived target architecture" FORCE)
    set(COSMO_NN_USE_SOPHON_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_CPU_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_RKNN_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_SOPHON_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_CPU_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_RK3588_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_DEFAULT_RESOURCE_DIR "${CMAKE_SOURCE_DIR}/data/resource/aiboxresource_x86")
    set(COSMO_MODEL_FILE_EXTENSIONS ".onnx")
    set(COSMO_MODEL_PRIMARY_EXTENSION ".onnx")
    set(COSMO_MODEL_DIR_TOKEN "X86")
    set(COSMO_ENGINE_TYPE "X86")
    set(COSMO_SUPPORTED_CHIP_TYPES "X86")
    set(COSMO_FFMPEG_SOURCE "prebuilt")
    set(COSMO_TARGET_TOOLCHAIN_FILE "")
elseif(COSMO_TARGET_PLATFORM STREQUAL "sophon")
    set(COSMO_TARGET_ARCH "aarch64" CACHE STRING "Derived target architecture" FORCE)
    set(COSMO_NN_USE_SOPHON_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_CPU_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_RKNN_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_SOPHON_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_CPU_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_RK3588_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_DEFAULT_RESOURCE_DIR "${CMAKE_SOURCE_DIR}/data/resource/aiboxresource")
    set(COSMO_MODEL_FILE_EXTENSIONS ".nn;.bmodel")
    set(COSMO_MODEL_PRIMARY_EXTENSION ".nn")
    set(COSMO_MODEL_DIR_TOKEN "SOPHGO")
    set(COSMO_ENGINE_TYPE "BM1688")
    set(COSMO_SUPPORTED_CHIP_TYPES "BM1688;CV186X")
    set(COSMO_FFMPEG_SOURCE "prebuilt")
    set(COSMO_TARGET_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/toolchains/aarch64-linux.toolchain.cmake")
elseif(COSMO_TARGET_PLATFORM STREQUAL "ascend310p3")
    set(COSMO_TARGET_ARCH "x86_64" CACHE STRING "Derived target architecture" FORCE)
    set(COSMO_NN_USE_SOPHON_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_CPU_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_RKNN_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_ASCEND_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_SOPHON_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_CPU_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_RK3588_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_ASCEND_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_DEFAULT_RESOURCE_DIR "${CMAKE_SOURCE_DIR}/data/resource/aiboxresource_ascend310p3")
    set(COSMO_MODEL_FILE_EXTENSIONS ".om")
    set(COSMO_MODEL_PRIMARY_EXTENSION ".om")
    set(COSMO_MODEL_DIR_TOKEN "ASCEND310P3")
    set(COSMO_ENGINE_TYPE "ASCEND310P3")
    set(COSMO_SUPPORTED_CHIP_TYPES "ASCEND310P3")
    set(COSMO_FFMPEG_SOURCE "system")
    set(COSMO_TARGET_TOOLCHAIN_FILE "")
else()
    set(COSMO_TARGET_ARCH "aarch64" CACHE STRING "Derived target architecture" FORCE)
    set(COSMO_NN_USE_SOPHON_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_CPU_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_NN_USE_RKNN_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_SOPHON_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_CPU_BACKEND OFF CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_MEDIA_USE_RK3588_BACKEND ON CACHE BOOL "Derived from COSMO_TARGET_PLATFORM" FORCE)
    set(COSMO_DEFAULT_RESOURCE_DIR "${CMAKE_SOURCE_DIR}/data/resource/aiboxresource_rk3588")
    set(COSMO_MODEL_FILE_EXTENSIONS ".rknn")
    set(COSMO_MODEL_PRIMARY_EXTENSION ".rknn")
    set(COSMO_MODEL_DIR_TOKEN "RK3588")
    set(COSMO_ENGINE_TYPE "RK3588")
    set(COSMO_SUPPORTED_CHIP_TYPES "RK3588")
    set(COSMO_FFMPEG_SOURCE "sysroot")
    set(COSMO_TARGET_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/toolchains/aarch64-linux.toolchain.cmake")
endif()

if(NOT DEFINED CACHE{RESOURCE_DIR})
    set(RESOURCE_DIR "${COSMO_DEFAULT_RESOURCE_DIR}" CACHE PATH "Resource directory" FORCE)
endif()

if(COSMO_TARGET_TOOLCHAIN_FILE AND
   NOT CMAKE_TOOLCHAIN_FILE)
    set(CMAKE_TOOLCHAIN_FILE "${COSMO_TARGET_TOOLCHAIN_FILE}"
        CACHE FILEPATH "Toolchain derived from COSMO_TARGET_PLATFORM")
endif()

if(COSMO_TARGET_ARCH STREQUAL "aarch64")
    if(NOT DEFINED CACHE{CMAKE_C_COMPILER} OR NOT "$CACHE{CMAKE_C_COMPILER}" MATCHES "aarch64")
        set(CMAKE_C_COMPILER "/usr/bin/aarch64-linux-gnu-gcc"
            CACHE FILEPATH "C compiler for aarch64 targets" FORCE)
    endif()
    if(NOT DEFINED CACHE{CMAKE_CXX_COMPILER} OR NOT "$CACHE{CMAKE_CXX_COMPILER}" MATCHES "aarch64")
        set(CMAKE_CXX_COMPILER "/usr/bin/aarch64-linux-gnu-g++"
            CACHE FILEPATH "CXX compiler for aarch64 targets" FORCE)
    endif()
    if(NOT DEFINED CACHE{CMAKE_AR} OR NOT "$CACHE{CMAKE_AR}" MATCHES "aarch64")
        set(CMAKE_AR "/usr/bin/aarch64-linux-gnu-ar"
            CACHE FILEPATH "Archiver for aarch64 targets" FORCE)
    endif()
    if(NOT DEFINED CACHE{CMAKE_RANLIB} OR NOT "$CACHE{CMAKE_RANLIB}" MATCHES "aarch64")
        set(CMAKE_RANLIB "/usr/bin/aarch64-linux-gnu-ranlib"
            CACHE FILEPATH "ranlib for aarch64 targets" FORCE)
    endif()
    if(NOT DEFINED CACHE{CMAKE_STRIP} OR NOT "$CACHE{CMAKE_STRIP}" MATCHES "aarch64")
        set(CMAKE_STRIP "/usr/bin/aarch64-linux-gnu-strip"
            CACHE FILEPATH "strip for aarch64 targets" FORCE)
    endif()
endif()
